// ===========================================
// Event-Gérance Pro — Configuration des Bulles
// ===========================================

import type { ConfigBulle } from '@/types'

export const BULLES_CONFIG: ConfigBulle[] = [
  {
    id: 1,
    nom: 'Commercial & I.A.',
    sousTitre: 'Devis, factures et assistant intelligent',
    icone: '💼',
    couleur: '#6366f1',
    couleurGradient: '#818cf8',
    lien: '/commercial',
    rolesAutorises: ['ADMIN', 'SECRETAIRE'],
  },
  {
    id: 2,
    nom: 'Gestion des Stocks',
    sousTitre: 'Inventaire et suivi du matériel',
    icone: '📦',
    couleur: '#8b5cf6',
    couleurGradient: '#a78bfa',
    lien: '/stocks',
    rolesAutorises: ['ADMIN', 'SECRETAIRE'],
  },
  {
    id: 3,
    nom: 'Planification',
    sousTitre: 'Tournées et logistique',
    icone: '🗓️',
    couleur: '#06b6d4',
    couleurGradient: '#22d3ee',
    lien: '/planification',
    rolesAutorises: ['ADMIN', 'SECRETAIRE'],
  },
  {
    id: 4,
    nom: 'Interface Terrain',
    sousTitre: 'Missions livreurs et signatures',
    icone: '🚛',
    couleur: '#10b981',
    couleurGradient: '#34d399',
    lien: '/terrain',
    rolesAutorises: ['ADMIN', 'LIVREUR'],
  },
  {
    id: 5,
    nom: 'Achats & Sous-location',
    sousTitre: 'Confrères et marges',
    icone: '🤝',
    couleur: '#f59e0b',
    couleurGradient: '#fbbf24',
    lien: '/achats',
    rolesAutorises: ['ADMIN', 'SECRETAIRE'],
  },
  {
    id: 6,
    nom: 'RH & Pointage',
    sousTitre: 'Personnel et heures GPS',
    icone: '👥',
    couleur: '#ef4444',
    couleurGradient: '#f87171',
    lien: '/rh',
    rolesAutorises: ['ADMIN'],
  },
  {
    id: 7,
    nom: 'Clients & Cautions',
    sousTitre: 'CRM et garanties',
    icone: '🏷️',
    couleur: '#ec4899',
    couleurGradient: '#f472b6',
    lien: '/clients',
    rolesAutorises: ['ADMIN', 'SECRETAIRE'],
  },
  {
    id: 8,
    nom: 'Réseaux Sociaux',
    sousTitre: 'Galerie et publications',
    icone: '📸',
    couleur: '#f97316',
    couleurGradient: '#fb923c',
    lien: '/reseaux-sociaux',
    rolesAutorises: ['ADMIN', 'SECRETAIRE', 'GESTIONNAIRE_WEB'],
  },
  {
    id: 9,
    nom: 'Direction',
    sousTitre: 'Statistiques et tableaux de bord',
    icone: '📊',
    couleur: '#14b8a6',
    couleurGradient: '#2dd4bf',
    lien: '/direction',
    rolesAutorises: ['ADMIN'],
  },
  {
    id: 10,
    nom: 'Administration',
    sousTitre: 'Permissions et comptabilité',
    icone: '⚙️',
    couleur: '#64748b',
    couleurGradient: '#94a3b8',
    lien: '/administration',
    rolesAutorises: ['ADMIN'],
  },
  {
    id: 11,
    nom: 'Atelier Vaisselle & Linge',
    sousTitre: 'Conditionnement, retours et blanchisserie',
    icone: '🧺',
    couleur: '#06b6d4',
    couleurGradient: '#22d3ee',
    lien: '/atelier',
    rolesAutorises: ['ADMIN', 'OPERATEUR_ATELIER'],
  },
  {
    id: 12,
    nom: 'Planning & Réservations',
    sousTitre: 'Calendrier des sorties, retours et tension des stocks',
    icone: '📅',
    couleur: '#8b5cf6',
    couleurGradient: '#c084fc',
    lien: '/planning',
    rolesAutorises: ['ADMIN', 'SECRETAIRE'],
  },
  {
    id: 13,
    nom: 'Cautions & Dépôts',
    sousTitre: 'Dépôts de garantie, encaissements et restitutions',
    icone: '🛡️',
    couleur: '#14b8a6',
    couleurGradient: '#2dd4bf',
    lien: '/cautions',
    rolesAutorises: ['ADMIN', 'SECRETAIRE'],
  },
  {
    id: 14,
    nom: 'Gestion Site Web',
    sousTitre: 'Catalogue en ligne, packs événements et livraison',
    icone: '🌐',
    couleur: '#8b5cf6',
    couleurGradient: '#a78bfa',
    lien: '/admin/web',
    rolesAutorises: ['ADMIN', 'GESTIONNAIRE_WEB'],
  },
]
